- name: download poetry installer
  get_url:
    url: "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py"
    dest: "/var/tmp/get-poetry.py"
  changed_when: False
  tags: [python, poetry]

- name: install poetry
  shell:
    cmd: "python /var/tmp/get-poetry.py --no-modify-path"
    creates: "$HOME/.poetry/bin/poetry"
  tags: [python, poetry]
    
