# https://taskfile.dev

version: "3"

tasks:
  default:
    deps: [update]

  update:
    desc: Update dotfiles.
    vars:
      STOW_PKGS:
        sh: ls -I justfile -I Taskfile.yml -I Makefile -I installers
    cmds:
      # Delete all symlinks. This deals with deleted config files.
      # Symlink files managed in this repo.
      - for pkg in ${STOW_PKGS} ; do stow -R {pkg} ; done
      - stow --target ~/bin --dir ~/code/user-land/ packaged

  systemctl:
    desc: Update systemctl user services.
    cmds:
      - systemctl --user daemon-reload
      - systemctl --user enable fusuma.service
      - systemctl --user enable ulauncher.service
