# github.com/go-task/task

version: '2'

tasks:

  default:
    desc: Run 'update'.
    deps: [update, ag]


  update:
    desc: Update dotfiles.
    cmds:
      - git pull
      # Delete all symlinks. This deals with deleted config files.
      - stow -D {{.stow_pkgs | catLines | replace " " " -D "}}
      # Symlink files managed in this repo.
      - stow -S {{.stow_pkgs | catLines | replace " " " -S "}}
    vars:
      stow_pkgs:
        sh: ls -I Taskfile.yml -I installers

  ag:
    cmds:
      - ln -s /usr/share/bash-completion/completions/ag ~/.bash.d/ag.bash
    status:
      - test -L ~/.bash.d/ag.bash


  awesome-libs:
    cmds:
      - cd ~/.config/awesome/ && git clone https://github.com/deficient/volume-control.git
