# github.com/go-task/task

version: '2'

includes:
  install: ./installers

tasks:

  default:
    desc: Run 'update'.
    deps: [update]


  update:
    desc: Update dotfiles.
    cmds:
      - git pull
      # Delete all symlinks. This deals with deleted config files.
      - stow -D {{.stow_pkgs | catLines | replace " " " -D "}}
      # Symlink files managed in this repo.
      - stow -S {{.stow_pkgs | catLines | replace " " " -S "}}
    vars:
      stow_pkgs:
        sh: ls -I Taskfile.yml -I installers

  awesome-libs:
    cmds:
      - cd ~/.config/awesome/ && git clone https://github.com/deficient/volume-control.git
