
# TODO: libevdev-devel yaml-cpp-devel
# TODO: mkdir /etc/interception

- name: install interception-tools
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - interception-tools
    - dual-function-keys
  become: true
  tags: [interception, interception-tools]

- name: ensure udevmon is running
  ansible.builtin.systemd:
    name: udevmon
    state: started
    enabled: true
  become: true
  tags: [interception, interception-tools]

- name: create config directory
  ansible.builtin.file:
    path: /etc/interception
    state: directory
    mode: '0755'

- name: install config udevmon.yaml
  ansible.builtin.copy:
    src: udevmon.yaml
    dest: /etc/interception/udevmon.yaml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - restart udevmon
  tags: [interception, interception-tools]

- name: install config dual.yaml
  ansible.builtin.copy:
    src: dual.yaml
    dest: /etc/interception/dual.yaml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - restart udevmon
  tags: [interception, interception-tools]
