- name: install interception-tools
  dnf:
    name: "interception-tools"
    state: present
  become: yes
  tags: [interception, interception-tools]

- name: ensure udevmon is running
  ansible.builtin.systemd:
    name: udevmon
    state: started
    enabled: true
  become: yes
  tags: [interception, interception-tools]


- name: check existence of dual-function-keys
  stat:
    path: /usr/local/bin/dual-function-keys
  register: dual_function_keys
  tags: [interception, interception-tools]


- name: dual-function-keys Git checkout
  ansible.builtin.git:
    repo: 'https://gitlab.com/interception/linux/plugins/dual-function-keys.git'
    dest: /tmp/dual-function-keys
  when: not dual_function_keys.stat.exists
  tags: [interception, interception-tools]

- name: compile dual-function-keys
  command:
    chdir: /tmp/dual-function-keys
    cmd: make
  when: not dual_function_keys.stat.exists
  tags: [interception, interception-tools]

- name: install dual-function-keys
  command:
    chdir: /tmp/dual-function-keys
    cmd: make install
  become: yes
  when: not dual_function_keys.stat.exists
  tags: [interception, interception-tools]

- name: install config udevmon.yaml
  ansible.builtin.copy:
    src: udevmon.yaml
    dest: /etc/interception/udevmon.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
    - restart udevmon
  tags: [interception, interception-tools]
    

- name: install config dual.yaml
  ansible.builtin.copy:
    src: dual.yaml
    dest: /etc/interception/dual.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
    - restart udevmon
  tags: [interception, interception-tools]
