# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  showIcons: true
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: delta --config ~/.config/lazygit/delta.config
# keybinding:
#   universal:
#     edit: <disabled> # disable 'edit file'
customCommands:
  - key: "l"
    context: "files"
    command: "( git status && git diff --cached && echo /commit-message-skill ) | claude"
    description: "Commit with Claude"
    output: terminal
  - key: "<c-d>"
    context: "localBranches"
    command: "gh dash"
    description: "gh dash"
    output: terminal
  - key: "<c-g>"
    context: "localBranches"
    command: "task pr"
    description: "task pr"
    output: terminal
