- name: Install binary as a fatfile
  get_url:
    dest: "/usr/local/sbin/{{ item.name }}"
    url: "{{ item.url }}"
  loop: "{{ fatbin }}"
  become: true
  tags: fatbin

- name: set permissions
  file:
    dest: "/usr/local/sbin/{{ item.name }}"
    mode: a+x
  loop: "{{ fatbin }}"
  become: true
  tags: fatbin
