#!/bin/bash
# postswitch

move_ws () {
    echo "[workspace=${1}]  move workspace to output ${2}" ;
    i3-msg "[workspace=${1}]  move workspace to output ${2}" ;
}

case "$AUTORANDR_CURRENT_PROFILE" in
    twobig)
        for ws in 1 2 3 4 5 6 7 8      ; do move_ws ${ws} HDMI-1 ; done
        for ws in 9 10                 ; do move_ws ${ws} DP-3   ; done
        ;;
    onebig)
        for ws in 1 2 3 4 5 6 7 8 9 10 ; do move_ws ${ws} HDMI-1 ; done
        ;;
    alone)
        for ws in 1 2 3 4 5 6 7 8 9 10 ; do move_ws ${ws} eDP-1  ; done
        ;;
    tv)
        for ws in 1 2 3 4 5 6 7 8      ; do move_ws ${ws} eDP-1  ; done
        for ws in 9 10                 ; do move_ws ${ws} HDMI-1 ; done
        ;;
esac

case "$AUTORANDR_CURRENT_PROFILE" in
    tv)
        pactl set-card-profile 0 output:hdmi-stereo+input:analog-stereo ;
        ;;
    *)
        pactl set-card-profile 0 output:analog-stereo+input:analog-stereo ;
        ;;
esac

~/bin/bar.sh
