#!/bin/bash
# postswitch

if [[ "$AUTORANDR_CURRENT_PROFILE" == 'alone' ]] ; then
    i3-msg '[workspace=1] move workspace to output eDP-1'
    i3-msg '[workspace=2] move workspace to output eDP-1'
    i3-msg '[workspace=3] move workspace to output eDP-1'
    i3-msg '[workspace=4] move workspace to output eDP-1'
    i3-msg '[workspace=5] move workspace to output eDP-1'
    i3-msg '[workspace=6] move workspace to output eDP-1'
    i3-msg '[workspace=7] move workspace to output eDP-1'
    i3-msg '[workspace=8] move workspace to output eDP-1'
    i3-msg '[workspace=9] move workspace to output eDP-1'
    i3-msg '[workspace=0] move workspace to output eDP-1'
else
    i3-msg '[workspace=1] move workspace to output HDMI-1'
    i3-msg '[workspace=2] move workspace to output HDMI-1'
    i3-msg '[workspace=3] move workspace to output HDMI-1'
    i3-msg '[workspace=4] move workspace to output HDMI-1'
    i3-msg '[workspace=5] move workspace to output HDMI-1'
    i3-msg '[workspace=6] move workspace to output HDMI-1'
    i3-msg '[workspace=7] move workspace to output HDMI-1'
    i3-msg '[workspace=8] move workspace to output HDMI-1'
    i3-msg '[workspace=9] move workspace to output eDP-1'
    i3-msg '[workspace=0] move workspace to output eDP-1'
fi

~/.config/i3/bar.sh
