- name: install python build dependencies
  dnf:
    name: "{{ rpm }}"
    state: present
  with_items:
    - make
    - gcc
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
    - tk-devel
    - libffi-devel
  become: yes
  tags: [python, pyenv, rpm]

- name: install pyenv
  shell:
    cmd: "curl https://pyenv.run | bash"
    creates: "$HOME/.pyenv"
  tags: [python, pyenv]
