#!/usr/bin/bash

dex-autostart -a -ebspwm -s ~/.config/autostart/ &
xset s 1800 10 && xss-lock -n /usr/libexec/xsecurelock/dimmer -l -- xsecurelock &

autorandr 1
bspc monitor HDMI-1 --reset-desktops 1 2 3 4 5 6 7 8
# bspc monitor DP-2 --reset-desktops 9

bspc config border_width         2
bspc config window_gap           0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.52
bspc config automatic_scheme     longest_side
bspc config initial_polarity     second_child
bspc config removal_adjustment   true

bspc config pointer_action1      move
# bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner

# bspc config pointer_follows_focus true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
