[plugins]
copier = 'https://github.com/amrox/asdf-pyapp'
fasd = 'https://github.com/funollet/asdf-fasd'
#icdiff = 'https://github.com/amrox/asdf-pyapp'

[tools]
act = "latest"
actionlint = "latest"
helm-diff = "latest"
terraform = "1.9.5"
sops = "latest"
lazygit = "latest"
pre-commit = "latest"
istioctl = "1.19.3"
argocd = "latest"
