[plugins]
copier = 'https://github.com/amrox/asdf-pyapp'
fasd = 'https://github.com/funollet/asdf-fasd'
#icdiff = 'https://github.com/amrox/asdf-pyapp'

[tools]
act = "latest"
actionlint = "latest"
helm-diff = "latest"
#icdiff = "latest"
terraform = "1.5.4"
sops = "latest"
