- name: linuxbrew dependencies
  dnf:
    name: [curl, file, git, libxcrypt-compat, '@Development Tools']
    state: present
  become: yes
  tags: brew

- command: mkdir -p /home/linuxbrew/.linuxbrew
  become: yes
  tags: brew
- command: "chown jordif: /home/linuxbrew/.linuxbrew"
  become: yes
  tags: brew
    
- name: install Linuxbrew
  command: /bin/bash -c "$(curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  tags: brew

- name: install with brew
  command: brew bundle
  tags: brew
