- name: install everything
  hosts: localhost

  tasks:
    - name: install repos
      dnf:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - fedora-workstation-repositories
        # - "http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm"
      tags: rpm

    # - replace:
    #     path: /etc/yum.repos.d/percona-release.repo
    #     regexp: '\$releasever'
    #     replace: '6'
    #   become: yes
    #   tags: rpm

    - name: "is google-chrome repo enabled?"
      shell: "dnf repoinfo google-chrome 2>/dev/null | grep '^Repo-status'"
      args:
        warn: false
      register: chrome_repo_enabled
      ignore_errors: true
      tags: rpm

    - name: enable chrome repo 
      command: "dnf config-manager --set-enabled google-chrome"
      when: '"enabled" not in chrome_repo_enabled.stdout'
      args:
        warn: false
      become: yes
      tags: rpm

    - name: remove unwanted packages with dnf
      dnf:
        name: "{{ rpm_absent }}"
        state: absent
      become: yes
      tags: rpm

    - name: install with dnf
      dnf:
        name: "{{ rpm }}"
        state: present
      become: yes
      tags: rpm

    - name: install aws-google-auth
      # build dependencies: libusb-devel systemd-devel
      command: pipx install aws-google-auth[u2f]
      args:
        creates: ~/.local/pipx/venvs/aws-google-auth
      tags: pipx

    - name: install with brew
      command: brew bundle
      tags: brew

    - group:
        name: uinput
      become: true
      tags: users

    - file:
        path: /dev/uinput
        owner: root
        group: uinput
        mode: 0640
      become: true
      tags: users

    - user:
        name: jordif
        append: yes
        groups:
          - wheel
          - dialout
          - input
          - uinput
          - docker
      become: true
      tags: users

    - name: Install binaries as fatfiles
      get_url:
        dest: "/usr/local/sbin/{{ item.name }}"
        url: "{{ item.url }}"
      loop: "{{ fatbin }}"
      become: true
      tags: fatbin

    - import_role:
        name: awscli
        tags: never
    - import_role:
        name: gems
    - import_role:
        name: pipx
    - import_role:
        name: flatpak
