- name: install everything
  hosts: localhost

  tasks:
    - import_role:
        name: rpm

    - name: install with brew
      command: brew bundle
      tags: brew

    - group:
        name: uinput
      become: true
      tags: users

    - file:
        path: /dev/uinput
        owner: root
        group: uinput
        mode: 0640
      become: true
      tags: users

    - user:
        name: jordif
        append: yes
        groups:
          - wheel
          - dialout
          - input
          - uinput
          - docker
      become: true
      tags: users

    - name: Install binaries as fatfiles
      get_url:
        dest: "/usr/local/sbin/{{ item.name }}"
        url: "{{ item.url }}"
      loop: "{{ fatbin }}"
      become: true
      tags: fatbin

    - import_role:
        name: awscli
        tags: never
    - import_role:
        name: gems
    - import_role:
        name: pipx
    - import_role:
        name: flatpak
