- name: install everything
  hosts: localhost

  tasks:
    - import_role:
        name: dnf

    - group:
        name: uinput
      become: true
      tags: users

    - file:
        path: /dev/uinput
        owner: root
        group: uinput
        mode: 0640
      become: true
      tags: users

    - user:
        name: jordif
        append: yes
        groups:
          - wheel
          - dialout
          - input
          - uinput
          - docker
      become: true
      tags: users

    - import_role:
        name: awscli
      tags: never
    - import_role:
        name: gems
    - import_role:
        name: pipx
    - import_role:
        name: flatpak
    - import_role:
        name: fatbin
    - import_role:
        name: brew
    - import_role:
        name: pyenv
    - import_role:
        name: poetry
    - import_role:
        name: udev
