# github.com/go-task/task

version: '2'

tasks:
  install:
    desc: Install not-packaged software.
    deps:
      - awless
      # - awscli
      - fonts-powerline
      - fonts-hack
      - vim_vundle

  awless:
    #desc: Install awless.
    dir: /tmp
    cmds:
      - wget -nv -c {{.URL}}
      - tar -xzf awless*tar.gz
      - sudo install awless /usr/local/bin/
    status:
      - which awless
    vars:
      VERSION: 0.1.11
      URL: https://github.com/wallix/awless/releases/download/v{{.VERSION}}/awless-linux-amd64.tar.gz

  fonts-powerline:
    #desc: Install fonts for Powerline on user's home.
    cmds:
      - cd ~/.fonts ; git clone https://github.com/Lokaltog/powerline-fonts
      - fc-cache -vf ~/.fonts
    status:
      - test -d ~/.fonts/powerline-fonts


  fonts-hack:
    #desc: Install font Hack from https://github.com/ryanoasis/nerd-fonts
    dir: /tmp
    cmds:
      - wget -nv -c {{.URL}}
      - test -d ~/.fonts/Hack && rm -r ~/.fonts/Hack || true
      - mkdir -p ~/.local/share/fonts/Hack
      - unzip -d ~/.local/share/fonts/Hack Hack.zip
      - fc-cache -fv
    status:
      - test -d ~/.local/share/fonts/Hack
    vars:
      URL: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip


  vim_vundle:
    #desc: Clone Vim Vundle to your ~/.vim/.
    cmds:
      - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    status:
      - test -d ~/.vim/bundle/Vundle.vim


  ################################################## 
  #

  config:
    desc: Post-install config tasks.
    cmds:
        # Set folder to store Virtualbox machines
      - VBoxManage setproperty machinefolder /home/jordif/spool/VirtualBox_VMs
      - sudo usermod -aG docker $(whoami)

  config-firefox:
    desc: Minor Firefox tweaks.
    cmds:
      - test -f ~/.gtkrc-2.0 || touch ~/.gtkrc-2.0
      - sed -i 's/# *gtk-key-theme-name =/gtk-key-theme-name =/' ~/.gtkrc-2.0
      - grep -q 'gtk-key-theme-name =' ~/.gtkrc-2.0 
        || echo 'gtk-key-theme-name = "Emacs"' >> ~/.gtkrc-2.0
        # Firefox uses kde file manager: requires xdg-desktop-portal-kde
        # Set the app launcher command to: GTK_USE_PORTAL=1 firefox %u

  config-kde:
    desc: KDE tweaks.
    cmds:
        # https://userbase.kde.org/Plasma/Tips
        # 'Meta' opens krunner
      # - kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.kglobalaccel,/component/krunner,org.kde.kglobalaccel.Component,invokeShortcut,run command"
      # - qdbus org.kde.KWin /KWin reconfigure
        #
        # 'Meta' does nothing by itself
      - kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta ""
      - qdbus org.kde.KWin /KWin reconfigure
