#!/bin/bash
# rofi-custom-menu

bluetooth-on () {
    local DEV
    DEV=$(bluetoothctl paired-devices | awk '/Soundpeats/ {print $2}')
    rfkill unblock bluetooth
    bluetoothctl connect "$DEV"
}

bluetooth-off () {
    local DEV
    DEV=$(bluetoothctl paired-devices | awk '/Soundpeats/ {print $2}')
    bluetoothctl disconnect "$DEV"
    rfkill block bluetooth
}

i3-move-workspace-to-output-next () {
    i3-msg 'move workspace to output next'
}

case $1 in
    bluetooth-on)       bluetooth-on > /dev/null ; exit ;;
    bluetooth-off)      bluetooth-off > /dev/null ; exit ;;
    i3-move-desktop)    i3-move-workspace-to-output-next > /dev/null ; exit ;;    
    vpntoggle)          vpntoggle > /dev/null ; exit ;;    
    *)                  echo vpntoggle
                        echo bluetooth-on
                        echo bluetooth-off
                        echo i3-move-desktop
                        ;;
esac
