[common]
quit = ["q"]

[bucket_list]
select = ["l", "enter"]
copy_details = ["y"]
refresh = ["ctrl-r"]
download = ["d"]
download_as = ["shift-d"]
sort = ["s"]
management_console = ["b"]

[object_list]
select = ["l", "enter"]
back = ["esc"]
reset_filter = ["shift-x"]
copy_details = ["y"]
refresh = ["ctrl-r"]
download = ["d"]
download_as = ["shift-d"]
sort = ["s"]
management_console = ["b"]

[object_detail]
back = ["esc"]
copy_details = ["y"]
download = ["d"]
download_as = ["shift-d"]
management_console = ["b"]

[object_preview]
back = ["esc"]

download = ["d"]
download_as = ["shift-d"]

encoding = ["e"]
toggle_wrap = ["w"]
toggle_number = ["n"]

[help]
close = ["?", "esc", "q"]
