
- name: install fusuma
  gem:
    name: "{{ item }}"
    state: present
    user_install: yes
  loop:
    - fusuma
    - fusuma-plugin-keypress
    - fusuma-plugin-tap
    - fusuma-plugin-sendkey
  tags: fusuma

- name: run fusuma
  systemd:
    name: fusuma
    enabled: yes
    scope: user
  tags: fusuma
